/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BingoDisplay: typeof import('./src/components/BingoDisplay.vue')['default']
    BingoDIsplay: typeof import('./src/components/BingoDIsplay.vue')['default']
    BingoInput: typeof import('./src/components/BingoInput.vue')['default']
  }
}
